List data = [
  {
    'id' : 1,
    'name' : 'Timex',
    'title' : 'Stainless',
    'price' : 500,
  },
  {
    'id' : 2,
    'name' : 'Boat Smart Watch',
    'title' : 'With gold bracelet',
    'price' : 1500,
  },
  {
    'id' : 3,
    'name' : 'Sonata',
    'title' : 'Best look',
    'price' : 1100,
  },
  {
    'id' : 4,
    'name' : 'Limestone',
    'title' : 'For mens',
    'price' : 2500,
  },
  {
    'id' : 5,
    'name' : 'casio',
    'title' : 'Both mens & Womens',
    'price' : 9000,
  },
  {
    'id' : 6,
    'name' : 'Timex',
    'title' : 'leather finish',
    'price' : 5000,
  },
  {
    'id' : 7,
    'name' : 'Titan',
    'title' : 'Silver look',
    'price' : 9500,
  },
  {
    'id' : 8,
    'name' : 'Fastrack',
    'title' : 'Stainless steel',
    'price' : 10000,
  },
  {
    'id' : 9,
    'name' : 'Fossil',
    'title' : 'wearable',
    'price' : 8000,
  },
  {
    'id' : 10,
    'name' : 'Sonata',
    'title' : 'wearable',
    'price' : 1500,
  },
  {
    'id' : 11,
    'name' : 'Sport',
    'title' : 'sport',
    'price' : 700,
  },
  {
    'id' : 12,
    'name' : 'Timex',
    'title' : 'Best of mens',
    'price' : 2500,
  },
  {
    'id' : 13,
    'name' : 'Citizen',
    'title' : 'for mens',
    'price' : 900,
  },
  {
    'id' : 14,
    'name' : 'htm',
    'title' : 'gold in color',
    'price' : 1000,
  },
  {
    'id' : 15,
    'name' : 'Boat',
    'title' : 'Smart',
    'price' : 1100,
  },
  {
    'id' : 16,
    'name' : 'fastrack',
    'title' : 'Sport',
    'price' : 1800,
  },
  {
    'id' : 17,
    'name' : 'Helix',
    'title' : 'black in color',
    'price' : 4500,
  },
  {
    'id' : 18,
    'name' : 'Titan',
    'title' : 'Premium',
    'price' : 2200,
  },
  {
    'id' : 19,
    'name' : 'Noice',
    'title' : 'best for you',
    'price' : 6500,
  },
  {
    'id' : 20,
    'name' : 'Boalt',
    'title' : 'Smart watch',
    'price' : 3500,
  },

];